#!/usr/bin/env node

/**
 * Unflat vs AI Agents Backtest Simulator
 *
 * Uses real historical APY data from data/historical-apy.json
 * (generated by scripts/fetch-apy.js).
 *
 * Strategies:
 *   - Unflat: Static 3-vault Morpho allocation
 *   - GPT-4o: Conservative bot (moves when APY gap >0.5%)
 *   - Claude Sonnet: Aggressive bot (always top 3 APY)
 *   - DeepSeek: Balanced bot (APY + TVL + safety weighted)
 *
 * Bots rebalance across 11 sources (9 Morpho + Aave v3 + Moonwell).
 *
 * Output: backtest-data.json
 */

const fs = require('fs');
const path = require('path');

// ============================================================================
// CONFIGURATION
// ============================================================================

const CONFIG = {
  startingCapital: 1000,
  durationDays: 365,
  gasPerRebalance: 2.50, // USD on Base
  slippagePerSwap: 0.002, // 0.2%
};

// Morpho vault ID → on-chain address (must match keys in historical-apy.json)
const VAULT_ADDRESSES = {
  'steakhouse-usdc':   '0xbeeF010f9cb27031ad51e3333f9aF9C6B1228183',
  're7-usdc':          '0x12AFDeFb2237a5963e7BAb3e2D46ad0eee70406e',
  'steakhouse-prime':  '0xBEEFE94c8aD530842bfE7d8B397938fFc1cb83b2',
  'steakhouse-hy':     '0xBEEFA7B88064FeEF0cEe02AAeBBd95D30df3878F',
  'moonwell-flagship': '0xc1256Ae5FF1cf2719D4937adb3bbCCab2E00A2Ca',
  'gauntlet-frontier': '0x236919F11ff9eA9550A4287696C2FC9e18E6e890',
  'clearstar-reactor': '0x1D3b1Cd0a0f242d598834b3F2d126dC6bd774657',
  'extrafi-xlend':     '0x23479229e52Ab6aaD312D0B03DF9F33B46753B5e',
  'gauntlet-prime':    '0xeE8F4eC5672F09119b96Ab6fB59C27E1b7e44b61',
};

// Vault metadata (tvl + volatility used by DeepSeek scoring)
const VAULTS = [
  { id: 'steakhouse-usdc',   name: 'Steakhouse USDC',    volatility: 0.15, tvl: 381e6 },
  { id: 're7-usdc',          name: 'Re7 USDC',           volatility: 0.12, tvl: 283e6 },
  { id: 'steakhouse-prime',  name: 'Steakhouse Prime',   volatility: 0.14, tvl: 82e6  },
  { id: 'steakhouse-hy',     name: 'Steakhouse HY v1.1', volatility: 0.22, tvl: 18e6  },
  { id: 'moonwell-flagship', name: 'Moonwell Flagship',  volatility: 0.18, tvl: 19e6  },
  { id: 'gauntlet-frontier', name: 'Gauntlet Frontier',  volatility: 0.20, tvl: 2.1e6 },
  { id: 'clearstar-reactor', name: 'Clearstar Reactor',  volatility: 0.28, tvl: 5.3e6 },
  { id: 'extrafi-xlend',     name: 'Extrafi XLend',      volatility: 0.25, tvl: 1.8e6 },
  { id: 'gauntlet-prime',    name: 'Gauntlet Prime',     volatility: 0.16, tvl: 15e6  },
];

// Unflat's static allocation
const UNFLAT_ALLOCATION = [
  { vaultId: 'steakhouse-hy', weight: 0.45 },
  { vaultId: 'moonwell-flagship', weight: 0.35 },
  { vaultId: 'steakhouse-usdc', weight: 0.20 },
];

// ============================================================================
// LOAD HISTORICAL DATA
// ============================================================================

function loadHistoricalData() {
  const dataPath = path.join(__dirname, 'data', 'historical-apy.json');
  if (!fs.existsSync(dataPath)) {
    console.error('❌ data/historical-apy.json not found. Run: node scripts/fetch-apy.js');
    process.exit(1);
  }

  const raw = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));

  // Build apyData: vaultId → [apy_day0, apy_day1, ...]
  const apyData = {};
  for (const [id, address] of Object.entries(VAULT_ADDRESSES)) {
    const series = raw.morpho[address];
    if (!series) {
      console.warn(`⚠ No data for ${id} (${address}), filling with zeros`);
      apyData[id] = new Array(CONFIG.durationDays).fill(0);
    } else {
      apyData[id] = series.slice(0, CONFIG.durationDays).map((p) => p.apy);
    }
  }

  // Protocol data: key → [apy_day0, apy_day1, ...]
  const protocolData = {};
  for (const [key, series] of Object.entries(raw.protocols)) {
    protocolData[key] = series.slice(0, CONFIG.durationDays).map((p) => p.apy);
  }

  console.log(`📂 Loaded ${Object.keys(apyData).length} Morpho vaults + ${Object.keys(protocolData).length} protocols`);
  console.log(`   Date range: ${raw.dateRange.from} → ${raw.dateRange.to}\n`);

  return { apyData, protocolData, dateRange: raw.dateRange };
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

function calculateWeightedAPY(allocation, allApyData, day) {
  return allocation.reduce((sum, { vaultId, weight }) => {
    const dailyAPY = allApyData[vaultId][day];
    return sum + (dailyAPY * weight);
  }, 0);
}

function dailyAccrual(capital, apyPercent) {
  return capital * (apyPercent / 100 / 365);
}

// Protocol metadata for the 2 non-Morpho sources (used by DeepSeek scoring)
const PROTOCOL_SOURCES = [
  { id: 'aave-usdc',     name: 'Aave v3 USDC',   protocol: 'aave',     volatility: 0.10, tvl: 100e6 },
  { id: 'moonwell-usdc', name: 'Moonwell USDC',   protocol: 'moonwell', volatility: 0.12, tvl: 7e6   },
];

// Unified asset pool: all 11 sources with metadata
const ALL_SOURCES = [
  ...VAULTS.map(v => ({ ...v, protocol: 'morpho' })),
  ...PROTOCOL_SOURCES,
];

// Build a merged APY lookup: sourceId → [apy_day0, ...]  (Morpho + protocols combined)
function buildUnifiedApyData(apyData, protocolData) {
  const unified = { ...apyData };
  for (const src of PROTOCOL_SOURCES) {
    unified[src.id] = protocolData[src.id];
  }
  return unified;
}

// Returns true when moving between different protocol families (morpho ↔ aave/moonwell)
function isCrossProtocol(fromId, toId) {
  const proto = (id) => {
    const src = ALL_SOURCES.find(s => s.id === id);
    return src ? src.protocol : 'morpho';
  };
  return proto(fromId) !== proto(toId);
}

// Calculate total gas for a rebalance, accounting for cross-protocol swaps.
// fromIds = current allocation IDs, toIds = new allocation IDs
function calcRebalanceGas(fromIds, toIds) {
  // Each position that changes incurs gas; cross-protocol swaps cost 2x
  let totalGas = 0;
  const exitIds = fromIds.filter(id => !toIds.includes(id));
  const enterIds = toIds.filter(id => !fromIds.includes(id));
  // Pair exits with enters; any unpaired still costs base gas
  const swapCount = Math.max(exitIds.length, enterIds.length);
  for (let i = 0; i < swapCount; i++) {
    const from = exitIds[i] || fromIds[0];
    const to = enterIds[i] || toIds[0];
    const multiplier = isCrossProtocol(from, to) ? 2 : 1;
    totalGas += CONFIG.gasPerRebalance * multiplier;
  }
  // If no positions actually changed but we still triggered, minimum 1 swap cost
  return totalGas || CONFIG.gasPerRebalance;
}

// ============================================================================
// STRATEGY IMPLEMENTATIONS
// ============================================================================

// Unflat: Static allocation, zero rebalances
function runUnflatStrategy(apyData) {
  let capital = CONFIG.startingCapital;
  let gasFees = 0;
  let rebalances = 0;
  const dailyValues = [];

  for (let day = 0; day < CONFIG.durationDays; day++) {
    const avgAPY = calculateWeightedAPY(UNFLAT_ALLOCATION, apyData, day);
    const earnings = dailyAccrual(capital, avgAPY);
    capital += earnings;
    dailyValues.push(capital);
  }

  return {
    name: 'Unflat (Static)',
    endingValue: capital,
    grossEarnings: capital - CONFIG.startingCapital,
    gasFees,
    slippageCosts: 0,
    totalFriction: 0,
    netEarnings: capital - CONFIG.startingCapital - gasFees,
    netReturn: ((capital - CONFIG.startingCapital) / CONFIG.startingCapital) * 100,
    rebalances,
    dailyValues,
  };
}

// GPT-4o: Conservative — only moves if APY gap >0.5% (searches all 11 sources)
function runGPT4oStrategy(allApyData) {
  let capital = CONFIG.startingCapital;
  let gasFees = 0;
  let slippageCosts = 0;
  let rebalances = 0;
  let currentAllocation = [
    { vaultId: 'steakhouse-hy', weight: 0.45 },
    { vaultId: 'moonwell-flagship', weight: 0.35 },
    { vaultId: 'gauntlet-frontier', weight: 0.20 },
  ];
  const dailyValues = [];

  for (let day = 0; day < CONFIG.durationDays; day++) {
    if (capital < 100) {
      const avgAPY = calculateWeightedAPY(currentAllocation, allApyData, day);
      const earnings = dailyAccrual(capital, avgAPY);
      capital += earnings;
      dailyValues.push(capital);
      continue;
    }

    const currentAPY = calculateWeightedAPY(currentAllocation, allApyData, day);

    // Rank ALL 11 sources by APY
    const ranked = ALL_SOURCES.map(s => ({
      ...s,
      dailyAPY: allApyData[s.id][day],
    })).sort((a, b) => b.dailyAPY - a.dailyAPY);

    const topThreeAPY = (ranked[0].dailyAPY + ranked[1].dailyAPY + ranked[2].dailyAPY) / 3;

    if (topThreeAPY - currentAPY > 0.5) {
      const newIds = ranked.slice(0, 3).map(s => s.id);
      const oldIds = currentAllocation.map(a => a.vaultId);
      const rebalanceCost = calcRebalanceGas(oldIds, newIds);
      const slippageCost = capital * CONFIG.slippagePerSwap * 3;
      gasFees += rebalanceCost;
      slippageCosts += slippageCost;
      capital -= (rebalanceCost + slippageCost);
      currentAllocation = newIds.map(id => ({ vaultId: id, weight: 1/3 }));
      rebalances++;
    }

    const avgAPY = calculateWeightedAPY(currentAllocation, allApyData, day);
    const earnings = dailyAccrual(capital, avgAPY);
    capital += earnings;
    dailyValues.push(capital);
  }

  return {
    name: 'GPT-4o Agent',
    endingValue: capital,
    grossEarnings: capital + gasFees + slippageCosts - CONFIG.startingCapital,
    gasFees,
    slippageCosts,
    totalFriction: gasFees + slippageCosts,
    netEarnings: capital - CONFIG.startingCapital,
    netReturn: ((capital - CONFIG.startingCapital) / CONFIG.startingCapital) * 100,
    rebalances,
    dailyValues,
  };
}

// Claude Sonnet: Aggressive — always top 3 APY from all 11 sources (daily rebalance if changed)
function runClaudeStrategy(allApyData) {
  let capital = CONFIG.startingCapital;
  let gasFees = 0;
  let slippageCosts = 0;
  let rebalances = 0;
  let currentAllocation = [...UNFLAT_ALLOCATION];
  const dailyValues = [];

  for (let day = 0; day < CONFIG.durationDays; day++) {
    if (capital < 100) {
      const avgAPY = calculateWeightedAPY(currentAllocation, allApyData, day);
      const earnings = dailyAccrual(capital, avgAPY);
      capital += earnings;
      dailyValues.push(capital);
      continue;
    }

    // Rank ALL 11 sources by APY
    const ranked = ALL_SOURCES.map(s => ({
      ...s,
      dailyAPY: allApyData[s.id][day],
    })).sort((a, b) => b.dailyAPY - a.dailyAPY);

    const topThree = ranked.slice(0, 3).map(s => s.id);

    const currentVaults = currentAllocation.map(a => a.vaultId).sort();
    const topThreeSorted = [...topThree].sort();

    if (JSON.stringify(currentVaults) !== JSON.stringify(topThreeSorted)) {
      const oldIds = currentAllocation.map(a => a.vaultId);
      const rebalanceCost = calcRebalanceGas(oldIds, topThree);
      const slippageCost = capital * CONFIG.slippagePerSwap * 3;
      gasFees += rebalanceCost;
      slippageCosts += slippageCost;
      capital -= (rebalanceCost + slippageCost);
      currentAllocation = topThree.map(id => ({ vaultId: id, weight: 1/3 }));
      rebalances++;
    }

    const avgAPY = calculateWeightedAPY(currentAllocation, allApyData, day);
    const earnings = dailyAccrual(capital, avgAPY);
    capital += earnings;
    dailyValues.push(capital);
  }

  return {
    name: 'Claude Sonnet Agent',
    endingValue: capital,
    grossEarnings: capital + gasFees + slippageCosts - CONFIG.startingCapital,
    gasFees,
    slippageCosts,
    totalFriction: gasFees + slippageCosts,
    netEarnings: capital - CONFIG.startingCapital,
    netReturn: ((capital - CONFIG.startingCapital) / CONFIG.startingCapital) * 100,
    rebalances,
    dailyValues,
  };
}

// DeepSeek: Balanced — weighted score (50% APY, 30% TVL, 20% safety) across all 11 sources
function runDeepSeekStrategy(allApyData) {
  let capital = CONFIG.startingCapital;
  let gasFees = 0;
  let slippageCosts = 0;
  let rebalances = 0;
  let currentAllocation = [
    { vaultId: 'clearstar-reactor', weight: 0.50 },
    { vaultId: 'extrafi-xlend', weight: 0.30 },
    { vaultId: 'moonwell-flagship', weight: 0.20 },
  ];
  const dailyValues = [];

  for (let day = 0; day < CONFIG.durationDays; day++) {
    if (capital < 100) {
      const avgAPY = calculateWeightedAPY(currentAllocation, allApyData, day);
      const earnings = dailyAccrual(capital, avgAPY);
      capital += earnings;
      dailyValues.push(capital);
      continue;
    }

    // Score ALL 11 sources
    const scored = ALL_SOURCES.map(s => {
      const apy = allApyData[s.id][day];
      const tvlScore = Math.log10(s.tvl) / 10;
      const safetyScore = (1 - s.volatility) * 5;
      const score = (apy * 0.5) + (tvlScore * 0.3) + (safetyScore * 0.2);
      return { ...s, score, dailyAPY: apy };
    }).sort((a, b) => b.score - a.score);

    const topThree = scored.slice(0, 3).map(s => s.id);

    const currentScore = currentAllocation.reduce((sum, { vaultId, weight }) => {
      const src = scored.find(s => s.id === vaultId);
      return sum + (src?.score || 0) * weight;
    }, 0);

    const topThreeScore = (scored[0].score + scored[1].score + scored[2].score) / 3;

    if (topThreeScore - currentScore > 0.3) {
      const oldIds = currentAllocation.map(a => a.vaultId);
      const rebalanceCost = calcRebalanceGas(oldIds, topThree);
      const slippageCost = capital * CONFIG.slippagePerSwap * 3;
      gasFees += rebalanceCost;
      slippageCosts += slippageCost;
      capital -= (rebalanceCost + slippageCost);
      currentAllocation = topThree.map(id => ({ vaultId: id, weight: 1/3 }));
      rebalances++;
    }

    const avgAPY = calculateWeightedAPY(currentAllocation, allApyData, day);
    const earnings = dailyAccrual(capital, avgAPY);
    capital += earnings;
    dailyValues.push(capital);
  }

  return {
    name: 'DeepSeek Agent',
    endingValue: capital,
    grossEarnings: capital + gasFees + slippageCosts - CONFIG.startingCapital,
    gasFees,
    slippageCosts,
    totalFriction: gasFees + slippageCosts,
    netEarnings: capital - CONFIG.startingCapital,
    netReturn: ((capital - CONFIG.startingCapital) / CONFIG.startingCapital) * 100,
    rebalances,
    dailyValues,
  };
}


// ============================================================================
// SIMULATION
// ============================================================================

function runSimulation() {
  console.log('🚀 Starting backtest simulation...\n');

  const { apyData, protocolData, dateRange } = loadHistoricalData();

  // Unified APY lookup for bot strategies (all 11 sources)
  const allApyData = buildUnifiedApyData(apyData, protocolData);

  // Run each strategy
  const results = [
    runUnflatStrategy(apyData),
    runGPT4oStrategy(allApyData),
    runClaudeStrategy(allApyData),
    runDeepSeekStrategy(allApyData),
  ];

  // Sort by net return (descending)
  results.sort((a, b) => b.netReturn - a.netReturn);

  // Calculate additional metrics
  results.forEach(result => {
    const dailyReturns = result.dailyValues.map((v, i) =>
      i === 0 ? 0 : (v - result.dailyValues[i-1]) / result.dailyValues[i-1]
    );
    const avgReturn = dailyReturns.reduce((a, b) => a + b, 0) / dailyReturns.length;
    const stdDev = Math.sqrt(
      dailyReturns.reduce((sum, r) => sum + Math.pow(r - avgReturn, 2), 0) / dailyReturns.length
    );
    result.sharpeRatio = stdDev > 0 ? (avgReturn / stdDev) : 0;

    let peak = result.dailyValues[0];
    let maxDD = 0;
    result.dailyValues.forEach(v => {
      if (v > peak) peak = v;
      const drawdown = (peak - v) / peak;
      if (drawdown > maxDD) maxDD = drawdown;
    });
    result.maxDrawdown = maxDD * 100;

    const positiveDays = dailyReturns.filter(r => r > 0).length;
    result.uptime = (positiveDays / CONFIG.durationDays) * 100;

    // Keep dailyValues for equity curve chart (round to 2 decimals to save space)
    result.dailyValues = result.dailyValues.map(v => Math.round(v * 100) / 100);
  });

  // Output JSON
  const output = {
    simulationPeriod: `${dateRange.from} to ${dateRange.to}`,
    startingCapital: CONFIG.startingCapital,
    durationDays: CONFIG.durationDays,
    gasPerRebalance: CONFIG.gasPerRebalance,
    strategies: results.map((r, i) => ({
      rank: i + 1,
      ...r,
    })),
  };

  const outputPath = path.join(__dirname, 'backtest-data.json');
  fs.writeFileSync(outputPath, JSON.stringify(output, null, 2));

  console.log('✅ Simulation complete!\n');
  console.log('📊 Results:\n');
  results.forEach((r, i) => {
    console.log(`${i+1}. ${r.name}`);
    console.log(`   Ending Value: $${r.endingValue.toFixed(2)}`);
    console.log(`   Net Return: ${r.netReturn.toFixed(2)}%`);
    console.log(`   Gas Fees: $${r.gasFees.toFixed(2)}`);
    console.log(`   Slippage: $${r.slippageCosts.toFixed(2)}`);
    console.log(`   Total Friction: $${r.totalFriction.toFixed(2)}`);
    console.log(`   Rebalances: ${r.rebalances}`);
    console.log(`   Sharpe: ${r.sharpeRatio.toFixed(2)}`);
    console.log('');
  });

  console.log(`📁 Output saved to: ${outputPath}\n`);
}

runSimulation();
